# Generated by Django 5.0 on 2024-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportGioLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Import Giờ Làm',
                'verbose_name_plural': 'Import Giờ Làm',
            },
        ),
        migrations.CreateModel(
            name='ImportNguoiLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Import Người Lao Động',
                'verbose_name_plural': 'Import Người Lao Động',
            },
        ),
    ]
