# Generated by Django 5.0 on 2024-04-20 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportData', '0001_initial'),
        ('Payroll', '0015_alter_importnguoild_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='importgiolam',
            name='quyetdinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payroll.quyetdinh', verbose_name='Quyết định tháng'),
        ),
        migrations.AddField(
            model_name='importgiolam',
            name='thang',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Lương tháng'),
        ),
    ]
