# Generated by Django 5.0 on 2024-05-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportData', '0005_alter_importgiolam_sogio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importgiolam',
            name='sogio',
            field=models.TimeField(blank=True, null=True, verbose_name='Số giờ làm việc'),
        ),
    ]
