# Generated by Django 5.0 on 2024-05-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImportData', '0007_remove_importgiolam_date_remove_importgiolam_mnv_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportGioLam',
            new_name='ImportGio',
        ),
        migrations.RenameModel(
            old_name='ImportNguoiLD',
            new_name='ImportNhanVien',
        ),
    ]
