# Generated by Django 5.0 on 2024-05-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuyetDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Quyết định tháng')),
                ('hesopt', models.FloatField(default=0.8, verbose_name='Hệ số part time')),
                ('luongcoso', models.IntegerField(default=1800000, verbose_name='Lương cơ sở')),
                ('muctang', models.FloatField(default=0.0, verbose_name='Mức tăng')),
            ],
            options={
                'verbose_name_plural': 'Quyết Định',
            },
        ),
    ]
