# Generated by Django 5.0 on 2024-05-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0033_alter_nguoild_quyetdinh_alter_capbac_qd_and_more'),
        ('QuyetDinh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuyetDinh',
            new_name='QuyetDinhLuong',
        ),
        migrations.AlterModelOptions(
            name='quyetdinhluong',
            options={'verbose_name_plural': 'Quyết Định Lương'},
        ),
    ]
