# Generated by Django 5.0 on 2024-05-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0033_alter_nguoild_quyetdinh_alter_capbac_qd_and_more'),
        ('QuyetDinh', '0003_quyetdinhtangbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='quyetdinhtangbac',
            name='bac_moi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_moi_quyetdinh_set', to='Payroll.hesoluong', verbose_name='Bậc mới'),
        ),
        migrations.AlterField(
            model_name='quyetdinhtangbac',
            name='bac_cu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_cu_quyetdinh_set', to='Payroll.hesoluong', verbose_name='Bậc cũ'),
        ),
    ]
