# Generated by Django 5.0 on 2024-05-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0033_alter_nguoild_quyetdinh_alter_capbac_qd_and_more'),
        ('QuyetDinh', '0004_quyetdinhtangbac_bac_moi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quyetdinhtangbac',
            options={'verbose_name_plural': 'Quyết Định Tăng Bậc'},
        ),
        migrations.AddField(
            model_name='quyetdinhtangbac',
            name='mnv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payroll.nguoild', verbose_name='Mã nhân viên'),
        ),
    ]
