# Generated by Django 4.2.7 on 2024-05-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuyetDinh', '0007_capbac_chucvu_hesoluong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quyetdinhtangbac',
            name='bac_cu',
        ),
        migrations.RemoveField(
            model_name='quyetdinhtangbac',
            name='bac_moi',
        ),
    ]
