# Generated by Django 5.0 on 2024-05-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuyetDinh', '0008_remove_quyetdinhtangbac_bac_cu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quyetdinhtangbac',
            name='bac_cu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_cu_quyetdinh_set', to='QuyetDinh.hesoluong', verbose_name='Bậc cũ'),
        ),
        migrations.AddField(
            model_name='quyetdinhtangbac',
            name='bac_moi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_moi_quyetdinh_set', to='QuyetDinh.hesoluong', verbose_name='Bậc mới'),
        ),
    ]
