# Generated by Django 5.0 on 2024-02-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cn', 'CN'), ('ks', 'KS'), ('b', 'B')], max_length=30)),
                ('des', models.CharField(max_length=30)),
                ('heso', models.TextField()),
            ],
        ),
    ]
