# Generated by Django 5.0 on 2024-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0002_hesoluong_quyetdinh_alter_capbac_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoild',
            name='thang',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lương tháng'),
        ),
    ]
