# Generated by Django 5.0 on 2024-03-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_alter_nguoild_thang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoild',
            name='loaihd',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=20, verbose_name='Loại hợp đồng'),
        ),
    ]
