# Generated by Django 5.0 on 2024-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0004_alter_nguoild_loaihd'),
    ]

    operations = [
        migrations.AddField(
            model_name='quyetdinh',
            name='bhyt',
            field=models.FloatField(default=0.235, verbose_name='Bảo hiểm y tế'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='hsdieuchinh',
            field=models.FloatField(default=0.9, verbose_name='Hệ số điều chỉnh'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='hsphucap',
            field=models.IntegerField(default=0, verbose_name='Hệ số phụ cấp'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='luongcoso',
            field=models.IntegerField(default=1800000, verbose_name='Lương cơ sở'),
        ),
        migrations.AlterField(
            model_name='hesoluong',
            name='bhyt',
            field=models.FloatField(blank=True, null=True, verbose_name='Bảo hiểm y tế'),
        ),
        migrations.AlterField(
            model_name='hesoluong',
            name='hsdieuchinh',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số điều chỉnh'),
        ),
        migrations.AlterField(
            model_name='hesoluong',
            name='hsphucap',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số phụ cấp'),
        ),
        migrations.AlterField(
            model_name='hesoluong',
            name='luongcoso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lương cơ sở'),
        ),
        migrations.AlterField(
            model_name='nguoild',
            name='mnv',
            field=models.CharField(max_length=10, verbose_name='MNV'),
        ),
    ]
