# Generated by Django 5.0 on 2024-03-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0006_alter_quyetdinh_hsphucap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesoluong',
            name='hsltheocap',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Hệ số lương theo cấp bậc'),
        ),
    ]
