# Generated by Django 5.0 on 2024-03-22 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0007_alter_hesoluong_hsltheocap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoild',
            name='cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Payroll.hesoluong', verbose_name='Cấp'),
        ),
    ]
