# Generated by Django 5.0 on 2024-03-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0009_remove_hesoluong_cap_hesoluong_bac_hesoluong_loaibac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesoluong',
            name='bac',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='loaibac',
        ),
    ]
