# Generated by Django 5.0 on 2024-03-25 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0010_remove_hesoluong_bac_remove_hesoluong_loaibac'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesoluong',
            name='bac',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bậc'),
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='loaibac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Payroll.capbac', verbose_name='Loại bậc'),
            preserve_default=False,
        ),
    ]
