# Generated by Django 5.0 on 2024-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0012_alter_nguoild_loaihd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoild',
            name='songay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số ngày đi làm'),
        ),
    ]
