# Generated by Django 4.1 on 2024-04-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payroll", "0013_alter_nguoild_songay"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportNguoiLD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="nguoild",
            name="thang",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                ],
                null=True,
                verbose_name="Lương tháng",
            ),
        ),
    ]
