# Generated by Django 5.0 on 2024-04-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0014_importnguoild_alter_nguoild_thang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importnguoild',
            options={'verbose_name': 'Import Người Lao Động', 'verbose_name_plural': 'Import Người Lao Động'},
        ),
    ]
