# Generated by Django 5.0 on 2024-04-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0015_alter_importnguoild_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kh', models.CharField(blank=True, max_length=5, null=True, verbose_name='Ký hiệu')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tên')),
                ('thuong', models.IntegerField(blank=True, null=True, verbose_name='Hệ số chức vụ')),
                ('qd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payroll.quyetdinh', verbose_name='Quyết định')),
            ],
            options={
                'verbose_name_plural': 'Chức Vụ',
            },
        ),
        migrations.DeleteModel(
            name='ImportNguoiLD',
        ),
    ]
