# Generated by Django 5.0 on 2024-04-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0016_chucvu_delete_importnguoild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chucvu',
            name='thuong',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số chức vụ'),
        ),
    ]
