# Generated by Django 5.0 on 2024-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0018_nguoild_chucvu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoild',
            name='songay',
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='giagiocong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá một giờ công'),
        ),
        migrations.AddField(
            model_name='nguoild',
            name='sogio',
            field=models.FloatField(blank=True, null=True, verbose_name='Số giờ làm việc'),
        ),
        migrations.AlterField(
            model_name='chucvu',
            name='thuong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thưởng phụ cấp'),
        ),
    ]
