# Generated by Django 5.0 on 2024-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0020_quyetdinh_sogio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quyetdinh',
            name='sogio',
            field=models.IntegerField(verbose_name='Giờ làm việc một ngày'),
        ),
    ]
