# Generated by Django 5.0 on 2024-04-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0022_alter_quyetdinh_sogio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoild',
            name='sogio',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Số giờ làm việc'),
        ),
    ]
