# Generated by Django 5.0 on 2024-04-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0023_alter_nguoild_sogio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chucvu',
            name='kh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ký hiệu'),
        ),
    ]
