# Generated by Django 5.0 on 2024-05-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0026_nguoild_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesoluong',
            name='bhyt',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='giangaycong',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='hsdieuchinh',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='hsphucap',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='bhyt',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='hsdieuchinh',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='hsphucap',
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='muctang',
            field=models.FloatField(default=0.0, verbose_name='Mức tăng'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='muctang',
            field=models.FloatField(default=0.0, verbose_name='Mức tăng'),
        ),
    ]
