# Generated by Django 5.0 on 2024-05-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0027_remove_hesoluong_bhyt_remove_hesoluong_giangaycong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capbac',
            name='cb',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ký hiệu'),
        ),
        migrations.AlterField(
            model_name='hesoluong',
            name='giagiocong',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá một giờ công'),
        ),
    ]
