# Generated by Django 5.0 on 2024-05-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0028_alter_capbac_cb_alter_hesoluong_giagiocong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesoluong',
            name='muctang',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='muctang',
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='bhyt',
            field=models.FloatField(blank=True, null=True, verbose_name='Bảo hiểm y tế'),
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='giangaycong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá một ngày công'),
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='hsdieuchinh',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số điều chỉnh'),
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='hsphucap',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số phụ cấp'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='bhyt',
            field=models.FloatField(default=0.235, verbose_name='Bảo hiểm y tế'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='hsdieuchinh',
            field=models.FloatField(default=0.9, verbose_name='Hệ số điều chỉnh'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='hsphucap',
            field=models.FloatField(default=0.0, verbose_name='Hệ số phụ cấp'),
        ),
        migrations.AlterField(
            model_name='capbac',
            name='cb',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ký hiệu'),
        ),
        migrations.AlterField(
            model_name='hesoluong',
            name='giagiocong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá một giờ công'),
        ),
    ]
