# Generated by Django 5.0 on 2024-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0029_remove_hesoluong_muctang_remove_quyetdinh_muctang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesoluong',
            name='bhyt',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='giagiocong',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='giangaycong',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='hsdieuchinh',
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='hsphucap',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='bhyt',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='hsdieuchinh',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='hsphucap',
        ),
        migrations.RemoveField(
            model_name='quyetdinh',
            name='sogio',
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='manhour',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lương cơ sở theo giờ'),
        ),
        migrations.AddField(
            model_name='hesoluong',
            name='muctang',
            field=models.FloatField(blank=True, null=True, verbose_name='Mức tăng'),
        ),
        migrations.AddField(
            model_name='quyetdinh',
            name='muctang',
            field=models.FloatField(default=0.0, verbose_name='Mức tăng'),
        ),
    ]
