# Generated by Django 5.0 on 2024-05-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0030_remove_hesoluong_bhyt_remove_hesoluong_giagiocong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capbac',
            name='cb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ký hiệu'),
        ),
    ]
