# Generated by Django 5.0 on 2024-05-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0031_alter_capbac_cb'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Lương tháng')),
                ('mnv', models.CharField(blank=True, max_length=10, null=True, verbose_name='MNV')),
                ('sogio', models.TimeField(blank=True, null=True, verbose_name='Số giờ làm việc')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Ngày làm việc')),
                ('quyetdinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payroll.quyetdinh', verbose_name='Quyết định tháng')),
            ],
            options={
                'verbose_name': 'Giờ Làm',
                'verbose_name_plural': 'Giờ Làm',
            },
        ),
    ]
