# Generated by Django 4.2.7 on 2024-05-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0033_alter_nguoild_quyetdinh_alter_capbac_qd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoild',
            name='cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payroll.hesoluong', verbose_name='Cấp bậc'),
        ),
    ]
