# Generated by Django 4.2.7 on 2024-05-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0035_bangluong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bangluong',
            options={'verbose_name_plural': 'Bảng Lương'},
        ),
    ]
