# Generated by Django 5.0 on 2024-05-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0037_alter_bangluong_mnv'),
        ('QuyetDinh', '0007_capbac_chucvu_hesoluong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesoluong',
            name='loaibac',
        ),
        migrations.RemoveField(
            model_name='chucvu',
            name='qd',
        ),
        migrations.AlterField(
            model_name='nguoild',
            name='chucvu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuyetDinh.chucvu', verbose_name='Chức vụ'),
        ),
        migrations.RemoveField(
            model_name='hesoluong',
            name='qd',
        ),
        migrations.AlterField(
            model_name='nguoild',
            name='cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuyetDinh.hesoluong', verbose_name='Cấp bậc'),
        ),
        migrations.DeleteModel(
            name='CapBac',
        ),
        migrations.DeleteModel(
            name='ChucVu',
        ),
        migrations.DeleteModel(
            name='HeSoLuong',
        ),
    ]
