# Generated by Django 5.0 on 2024-05-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0038_remove_hesoluong_loaibac_remove_chucvu_qd_and_more'),
        ('QuyetDinh', '0009_quyetdinhtangbac_bac_cu_quyetdinhtangbac_bac_moi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoild',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='nguoild',
            name='luong',
        ),
        migrations.RemoveField(
            model_name='nguoild',
            name='quyetdinh',
        ),
        migrations.RemoveField(
            model_name='nguoild',
            name='sogio',
        ),
        migrations.RemoveField(
            model_name='nguoild',
            name='thang',
        ),
        migrations.AddField(
            model_name='bangluong',
            name='cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuyetDinh.hesoluong', verbose_name='Cấp bậc'),
        ),
        migrations.AddField(
            model_name='bangluong',
            name='luong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lương'),
        ),
        migrations.AddField(
            model_name='bangluong',
            name='sogio',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Số giờ làm việc'),
        ),
    ]
