# Generated by Django 4.2.7 on 2024-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0039_remove_nguoild_cap_remove_nguoild_luong_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bangluong',
            options={'verbose_name_plural': 'Thông Tin Lương'},
        ),
        migrations.AlterField(
            model_name='giolam',
            name='sogio',
            field=models.FloatField(blank=True, null=True, verbose_name='Số giờ làm việc'),
        ),
    ]
