# Generated by Django 4.2.11 on 2024-05-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Payroll", "0039_remove_nguoild_cap_remove_nguoild_luong_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bangluong",
            options={"verbose_name_plural": "Thông Tin Lương"},
        ),
    ]
