# Generated by Django 4.2.11 on 2024-05-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Payroll", "0040_alter_bangluong_options"),
        ("Payroll", "0040_alter_bangluong_options_alter_giolam_sogio"),
    ]

    operations = []
