# Generated by Django 5.0 on 2024-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0042_bangluong_canhbao'),
    ]

    operations = [
        migrations.AddField(
            model_name='giolam',
            name='canhbao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cảnh báo'),
        ),
    ]
